Update all Endpoint scoring files to point to model as a directory in…
Azure/azureml-examples pull request #1306
Opened 2022-05-13 20:21 UTC by Chris113113

…stead of as a file

# PR into Azure/azureml-examples

## Checklist

I have:

- [ ] read and followed the contributing guidelines

## Changes

-

fixes #

2022-05-13 22:30 UTC, rsethur commented
Thanks for fixing this. Please ensure you touch all of the workflow files (in .github/workflows) and ensure they are ALL tested before merging this
![image](https://user-images.githubusercontent.com/9762186/168397002-8739e4b5-e172-4753-a11a-075be36dc58c.png)

2022-05-13 23:35 UTC, rsethur commented
@Chris113113  you also need to add workflow files for deploy-local-endpoint and deploy-moe-autoscale.
Ignore the failure for uai - its a known issue and someone is fixing it (cli-scripts-deploy-managed-online-endpoint-access-resource-uai)

2022-05-13 23:56 UTC, rsethur requested changes

2022-05-13 23:56 UTC, rsethur commented on .github/workflows/cli-scripts-deploy-managed-online-endpoint-access-resource-sai.yml
> +      - cli/endpoints/online/managed/managed-identity
did you mean this folder instead?: cli/endpoints/online/managed/managed-identities

2022-05-13 23:56 UTC, rsethur commented on .github/workflows/cli-scripts-deploy-managed-online-endpoint-access-resource-uai.yml
> +      - cli/endpoints/online/managed/managed-identity
did you mean this folder instead?: cli/endpoints/online/managed/managed-identities

2022-05-13 23:56 UTC, rsethur commented on .github/workflows/cli-scripts-deploy-managed-online-endpoint-mlflow.yml
> +      - cli/endpoints/online/managed
this does not seem to be required for mlflow sample

2022-05-13 23:56 UTC, rsethur commented on .github/workflows/cli-scripts-deploy-managed-online-endpoint.yml
> +      - cli/endpoints/online/managed
Needs to be this: endpoints/online/managed/sample
The above path lots of stuff not needed by this script

2022-05-13 23:56 UTC, rsethur commented on .github/workflows/cli-scripts-deploy-safe-rollout-online-endpoints.yml
> +      - cli/endpoints/online/managed
Needs to be this: endpoints/online/managed/sample
The above path lots of stuff not needed by this script

2022-05-14 00:09 UTC, rsethur requested changes

2022-05-14 00:13 UTC, rsethur approved these changes

2022-05-16 21:32 UTC, raghutillu approved these changes

2022-05-17 03:28 UTC, merged