Updated the Tutorial
Azure/azureml-examples pull request #1421
Opened 2022-06-14 23:33 UTC by AliMahmoudzadeh

# PR into Azure/azureml-examples

## Checklist

I have:

- [ x] read and followed the contributing guidelines

## Changes
- Added various links to the AML documentation

fixes #
- Updated the dependencies in the environment

2022-06-14 23:47 UTC, jfomhover approved these changes

2022-06-15 00:07 UTC, sdgilley requested changes

2022-06-15 00:07 UTC, sdgilley commented on tutorials/e2e-ds-experience/e2e-ml-workflow.ipynb
> +    "Registering the Data asset will enable you to:\n",
```suggestion
    "Registering the data asset will enable you to:\n",
```

2022-06-15 00:07 UTC, sdgilley commented on tutorials/e2e-ds-experience/e2e-ml-workflow.ipynb
> +    "* reuse and share the Data asset in future pipelines\n",
```suggestion
    "* reuse and share the data asset in future pipelines\n",
```

2022-06-15 00:07 UTC, sdgilley commented on tutorials/e2e-ds-experience/e2e-ml-workflow.ipynb
> +    "* use versions to track the modification to the Data asset\n",
```suggestion
    "* use versions to track the modification to the data asset\n",
```

2022-06-15 00:07 UTC, sdgilley commented on tutorials/e2e-ds-experience/e2e-ml-workflow.ipynb
> +    "Now deploy your machine learning model as a web service in the Azure cloud, an [`online endpoint`](https://docs.microsoft.com/en-us/azure/machine-learning/concept-endpoints).\n",
```suggestion
    "Now deploy your machine learning model as a web service in the Azure cloud, an [`online endpoint`](https://docs.microsoft.com/azure/machine-learning/concept-endpoints).\n",
```

2022-06-15 21:58 UTC, AliMahmoudzadeh commented
@sdgilley, I committed your suggestions, but it seems that the merge is still blocked, would you please manually approve if it is acceptable now. Thanks.

2022-06-15 22:15 UTC, sdgilley approved these changes

2022-06-15 22:16 UTC, merged