update sweep in pipelines
Azure/azureml-examples pull request #1711
Opened 2022-10-01 01:21 UTC by sharma-riti

# PR into Azure/azureml-examples

## Checklist

I have:

- [ ] read and followed the contributing guidelines

## Changes

-

fixes #

2022-10-01 06:15 UTC, shubhamiit commented
Could you fix the smoke/Build and failing workflow for OD and IS?

2022-10-01 06:19 UTC, shubhamiit requested changes
Could you fix the smoke/Build and failing workflow for OD and IS?

2022-10-01 06:20 UTC, shubhamiit approved these changes
Could you fix the smoke/Build and failing workflow for OD and IS?

2022-10-03 02:28 UTC, MadhuM02 approved these changes

2022-10-03 05:40 UTC, merged