CLI Example Registered Model
Azure/azureml-examples pull request #1800
Opened 2022-10-25 19:55 UTC by xanwal

# PR into Azure/azureml-examples

## Checklist

I have:

- [x] read and followed the contributing guidelines

## Changes

- Added example for a pre-registered model (CLI Version)

fixes #

2022-10-26 04:35 UTC, shohei1029 requested changes

2022-10-26 04:35 UTC, shohei1029 commented on cli/deploy-moe-minimal-single-model-registered.sh
> +#set -e
Could you uncomment this? This will bypass our build test.
```suggestion
set -e
```

2022-10-26 13:59 UTC, DannyBruno approved these changes

2022-10-26 16:45 UTC, shmahe approved these changes

2022-10-27 04:12 UTC, shohei1029 approved these changes

2022-10-27 04:12 UTC, merged