Add SDK and CLI example for OpenAPI/Swagger
Azure/azureml-examples pull request #1821
Opened 2022-10-31 09:39 UTC by xanwal

# Description

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/Azure/azureml-examples/blob/main/CONTRIBUTING.md)
- [x] Pull request includes test coverage for the included changes.

2022-11-01 07:27 UTC, shohei1029 requested changes

2022-11-01 07:27 UTC, shohei1029 commented
The runner for SDK (sdk-endpoints-online-managed-online-endpoints-openapi) seems to be failed.

2022-11-02 03:13 UTC, shohei1029 commented on sdk/python/endpoints/online/managed/online-endpoints-openapi.ipynb
> +    "Custom swagger files can be integrated by inclduing them at the root of the `code` directory. The custom file should be named `swagger<version>.json` i.e. `swagger2.json`. "
typo

2022-11-02 03:17 UTC, shohei1029 commented on sdk/python/endpoints/online/managed/online-endpoints-openapi.ipynb
> +    "The AzureML Inference Server automatically generates swagger files for scoring scripts that use [Inference Schema](https://github.com/Azure/InferenceSchema). In this example, a simple Inference
Is the link to [Inference Schema example](../inference-schema) broken?

2022-11-08 02:47 UTC, shohei1029 approved these changes

2022-11-16 06:58 UTC, dem108 approved these changes
Looks great. Thanks!

2022-11-16 07:08 UTC, merged