remove news summary dataset from repo, download using script in sample
Azure/azureml-examples pull request #2250
Opened 2023-05-04 21:23 UTC by ManojBableshwar

# Description

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/Azure/azureml-examples/blob/main/CONTRIBUTING.md)
- [ ] Pull request includes test coverage for the included changes.

2023-05-05 15:50 UTC, adrosa approved these changes

2023-05-05 16:16 UTC, adrosa requested changes

2023-05-05 16:16 UTC, adrosa commented on sdk/python/foundation-models/system/finetune/summarization/news-summary.ipynb
> +    "    \"./news-summary-dataset/small_test.jsonl\", orient=\"records\", lines=True\n",
this does not solve the copyright issue

2023-05-05 23:24 UTC, adrosa commented on sdk/python/foundation-models/system/finetune/summarization/news-summary.ipynb
> +    "        subscription_id = \"<SUBSCRIPTION_ID>\"\n",
done!

2023-05-08 14:40 UTC, adrosa commented
to appease black
```
pip install "black[jupyter]"
black cli/foundation-models/system/finetune/summarization/download-dataset.py
black sdk/python/foundation-models/system/finetune/summarization/news-summary.ipynb
```

2023-05-09 16:03 UTC, Man-MSFT approved these changes

2023-05-09 16:04 UTC, Man-MSFT commented on cli/foundation-models/system/finetune/summarization/download-dataset.py
> +import os
already imported on line 1

2023-05-09 16:04 UTC, Man-MSFT commented on cli/foundation-models/system/finetune/summarization/news-summary.sh
> +subscription_id="21d8f407-c4c4-452e-87a4-e609bfb86248" #"<SUBSCRIPTION_ID>"
What ID is this?

2023-05-09 16:05 UTC, Man-MSFT commented on cli/foundation-models/system/finetune/summarization/news-summary.sh
> +subscription_id="21d8f407-c4c4-452e-87a4-e609bfb86248" #"<SUBSCRIPTION_ID>"
Looks like there are test values left here, we need to remove these

2023-05-09 16:06 UTC, Man-MSFT commented on cli/foundation-models/system/finetune/summarization/download-dataset.py
> +import pandas as pd
already imported way up top

2023-05-09 16:06 UTC, adrosa approved these changes

2023-05-09 16:20 UTC, chrjia approved these changes

2023-05-10 07:18 UTC, ManojBableshwar commented
will implement changes suggested by Man in a new PR as i need to get this in quick to unblock //build deliverables

2023-05-10 15:28 UTC, adrosa approved these changes

2023-05-10 15:33 UTC, akshaya-a approved these changes
follow up to address comments

2023-05-10 15:39 UTC, merged