MMD OD/IS sdk, cli examples; Update HuggingFace Classification examples
Azure/azureml-examples pull request #2477
Opened 2023-07-24 13:28 UTC by rjaincc

# Description
* Update Classification examples with latest updates
* Introduce MMD OD and IS sdk and cli examples. 

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/Azure/azureml-examples/blob/main/CONTRIBUTING.md)
- [x] I have coordinated with the docs team (mldocs@microsoft.com) if this PR deletes files or changes any file names or file extensions.
- [x] Pull request includes test coverage for the included changes.

2023-07-27 04:45 UTC, MadhuM02 commented on cli/foundation-models/system/finetune/image-classification/multilabel-classification/hftransformers-fridgeobjects-multilabel-classification-pipeline.yaml
> -      auto_hyperparameter_selection: False
Should we also remove the params which are picked up from defaults??

2023-07-27 05:17 UTC, MadhuM02 commented on sdk/python/foundation-models/system/finetune/image-object-detection/mmdetection-fridgeobjects-object-detection.ipynb
> +    "        size=\"Standard_NC6\",\n",
change this to Standard_NC6s_v3??

2023-07-27 05:19 UTC, MadhuM02 commented on cli/foundation-models/system/finetune/image-instance-segmentation/mmdetection-fridgeobjects-instance-segmentation.sh
> +number_of_gpu_to_use_finetuning=$gpus_per_node # set to the number of GPUs available in the compute
number_of_gpu_to_use_finetuning -> process_count_per_instance??

2023-07-27 08:03 UTC, gauravrajguru commented on cli/foundation-models/system/finetune/image-instance-segmentation/mmdetection-fridgeobjects-instance-segmentation-pipeline.yml
> +      number_of_epochs: 15
do we need to remove HP values if auto selection is on?

2023-07-27 09:13 UTC, gauravrajguru requested changes

2023-07-27 09:13 UTC, gauravrajguru commented on sdk/python/foundation-models/system/finetune/image-instance-segmentation/mmdetection-fridgeobjects-instance-segmentation.ipynb
> +    "| TODO | azureml-preview registry |"
can be updated

2023-08-01 10:09 UTC, rjaincc commented on sdk/python/foundation-models/system/finetune/image-classification/multiclass-classification/hftransformers-fridgeobjects-multiclass-classification.ipynb
> -    "    \"auto_hyperparameter_selection\": False,\n",
We are not. This parameter has been taken out.

2023-08-01 10:10 UTC, rjaincc commented on sdk/python/foundation-models/system/docs/component_docs/image_finetune/transformers_finetune_component.md
> -4. _auto_hyperparameter_selection_ (bool, optional)
We don't have it anymore. No defaults on the UI, anything that user mentioned will be picked else will come from hierarchy.

2023-08-01 10:11 UTC, rjaincc commented on sdk/python/foundation-models/system/docs/component_docs/image_finetune/mmd_finetune_component.md
> +1. _model_path_ (URI_FOLDER, required)
We don't have it anymore.

2023-08-03 08:09 UTC, gauravrajguru approved these changes

2023-08-03 10:31 UTC, merged