FL resources
Azure/azureml-examples pull request #947
Opened 2021-12-17 23:19 UTC by thomasp-ms

First set of files to support Federated Learning. 

- `automated_provisioning`: resources for automatically provisioning the FL setup
- `fl_arc_k8s`: example using the FL API
- `plan` directory: a generic plan for how to onboard

See more details in the ReadMe's

2021-12-20 19:25 UTC, dkmiller requested changes

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/README.md
> +Azure ML is working on first-class support for cross-silo federated learning.
Suggestion: add clarification that there isn't yet a committed timeline.

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/automated_provisioning/ReadMe.md
> +- `SubscriptionId`: the Id of the subscription where the silo will be created (default: "48bbc269-ce89-4f6f-9a12-c6f91fcb772d", _a.k.a._ the AIMS subscription).
Suggestion: remove the default, since this subscription ID won't mean anything outside our team.

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/automated_provisioning/ReadMe.md
> +- `SubscriptionId_Orchestrator`: the Id of the subscription to which the orchestrator will belong (default: "48bbc269-ce89-4f6f-9a12-c6f91fcb772d", _a.k.a._ the AIMS subscription).
Same "nit" about removing default value, ditto for e.g. workspace name, resource group, etc.

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/automated_provisioning/ReadMe.md
> +```ps1
Nit: `ps1` &mapsto; `ps` or `powershell` here and in the other places you type sample PowerShell commands, i.e.

```markdown
    ```powershell
    ./ps/ConnectSiloToOrchestrator.ps1  "..."
    ```
```

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/automated_provisioning/ReadMe.md
> +- Add more validation on input strings.
Suggestion: future work to validate all silos at once.

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/automated_provisioning/bicep/AMLWorkspace.bicep
> +var tenantId = subscription().tenantId
Suggestion: add some newlines to separate parameters, variables, and resources.

E.g.,

```bicep
@description('Specifies whether to reduce telemetry collection and enable additional encryption.')
param hbi_workspace bool = false

var tenantId = subscription().tenantId

resource storageAccountName 'Microsoft.Storage/storageAccounts@2021-06-01' = {
    ...
```

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/automated_provisioning/ReadMe.md
> +1. Have access to an Azure subscription.
Nit: also need PowerShell, ideally PowerShell Core since that's cross-platform.

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/automated_provisioning/ps/Utils.ps1
> +function Wait-For-Successful-Registration(){
Nit: PowerShell method names should look like `Verb-OtherStuff`, e.g. below. Ditto for the other method names in this file.

```powershell
Wait-SuccessfulRegistration
```

These articles provide helpful context:

- [Approved Verbs for PowerShell Commands](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.2)
- [Strongly Encouraged Development Guidelines](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/strongly-encouraged-development-guidelines?view=powershell-7.2)

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/automated_provisioning/ps/Utils.ps1
> +        Write-Output "Compute name $ComputeName is invalid. It can include letters, digits and dashes. It must start with a letter, end with a letter or digit, and be between 2 and 16 characters in l
Suggestion: `Write-Error` here since it's an error message.

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/automated_provisioning/ps/Utils.ps1
> +function Wait-For-Successful-Registration(){
Nit: `utils` and `helpers` are not great things to name files. Something like `AzureUtilities` is a bit better.

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/automated_provisioning/sample_job/RunSampleJob.ps1
> +    az ml dataset create --resource-group $ResourceGroup --workspace-name $WorkspaceName --name $DatasetName --local-path "./sample_job/src/mnist_data/"
Is there a way you can create this dataset from a remote path? E.g. like

https://github.com/dkmiller/tidbits/blob/master/2021/2021-11-04_mnist-e2e/data/mnist_train_images_raw/data.yml

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/fl_arc_k8s/README.md
> +- Clone the current repository and set `accelerators\federated-learning\fl_arc_k8s` as your working directory.
Suggestion: create a Conda environment file capturing these steps. Then the guidelines are as simple as `conda env create --file environment.yml`.

```yaml
name: fl-shrike-examples-env-py38

dependencies:

- python=3.8
- pip
- pip:
  - -r requirements.txt
```

2021-12-20 19:25 UTC, dkmiller commented on accelerators/federated-learning/fl_arc_k8s/components/add_one_thousand_to_parameter/component_spec.yaml
> +tags:
Nit: suggest removing tags mentioning `aml-ds@microsoft.com`.

2021-12-21 19:05 UTC, lostmygithubaccount requested changes
tagging @balapv 

The extension used in these files is `.yaml`, whereas the rest of the repo (with possible exceptions that slipped in) are using `.yml`. We should be consistent, though the choice to use `.yml` was arbitrarily made by me.

2021-12-21 19:25 UTC, dkmiller commented
> tagging @balapv
> 
> The extension used in these files is `.yaml`, whereas the rest of the repo (with possible exceptions that slipped in) are using `.yml`. We should be consistent, though the choice to use `.yml` was arbitrarily made by me.

@lostmygithubaccount , consensus is that `YAML` is better ( https://stackoverflow.com/questions/22268952 ) and some tooling (e.g., [Hydra](http://hydra.cc/)) requires it.

Note, the YAML files aren't DPv2 YAML files, they're config files for libraries being used in defining pipelines.

2021-12-23 01:37 UTC, lostmygithubaccount commented
@dkmiller quite a sparse FAQ! https://yaml.org/faq.html 

Understood these aren't DPv2, but we should be consistent across the repository regardless. I'm not personally opposed to switching to `.yaml` at all, but it would require a bit of updating (the DPv2 YAMLs, the GHA workflow definitions, and in certain `readme.py` files that assume `.yml`, possibly other locations). @balapv and @paulshealy1 can help drive the change if agreed on switching.

2021-12-23 01:43 UTC, thomasp-ms commented
> @dkmiller quite a sparse FAQ! https://yaml.org/faq.html
> 
> Understood these aren't DPv2, but we should be consistent across the repository regardless. I'm not personally opposed to switching to `.yaml` at all, but it would require a bit of updating (the DPv2 YAMLs, the GHA workflow definitions, and in certain `readme.py` files that assume `.yml`, possibly other locations). @balapv and @paulshealy1 can help drive the change if agreed on switching.

@lostmygithubaccount so you're saying this PR should be blocked until all YAML files in the repo are renamed? It seems like it might not be such a small change. Any way this other can happen after this PR gets merged?

2021-12-23 01:55 UTC, lostmygithubaccount commented
@thomasp-ms not saying we should block the PR on this issue, just pointing it out since we tend to let inconsistencies like these into our examples and then never fix/they get worse over time. 

As long as we're aware and plan to fix, not a huge concern -- and not a huge concern regardless for this PR (just want to ensure Bala and Paul are aware of the discussion and potential inconsistency). 

That said, I would like us to have a discussion on where we host accelerators (in this repo or elsewhere) post-holidays with the other Microsoft teams driving that effort. If there's some urgent need to merge this into the main branch, I think it's fine to proceed. We can always move and redirect the content later if we do decide it should live elsewhere.

2022-01-06 17:32 UTC, dkmiller commented
Per internal discussion, this content will be added to the following repo instead:

> https://github.com/Azure-Samples/azure-ml-federated-learning/

2022-01-06 17:32 UTC, closed without merging